//! The [`Job`] data model and the versioned, on-disk store envelope.
//!
//! A job is the unit a schedule fires. The struct is pure data: the cli crate's
//! `FileJobStore` is responsible for actually reading and writing it. The two
//! envelope helpers here ([`parse_jobs`] / [`jobs_to_json`]) own the wire format
//! and the schema-version check, so the store can stay a thin byte-mover.

use std::path::PathBuf;

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

use crate::schedule::{compute_next_run, Schedule};

/// The persisted store-envelope schema version. A file whose version does not
/// match is refused rather than silently misread.
pub const JOBS_SCHEMA_VERSION: &str = "codex-cron.jobs.v1";

/// Which backend runs a job when it fires.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, Default)]
#[serde(rename_all = "lowercase")]
pub enum ExecutorKind {
    /// The OpenAI `codex` CLI agent (the default).
    #[default]
    Codex,
    /// A raw shell script.
    Shell,
    /// A governed `ao2 run`.
    Ao2,
}

/// Where a job is in its lifecycle.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum JobState {
    /// Waiting for its next firing instant.
    Scheduled,
    /// Currently executing (advanced-before-run; guards against double-fire).
    Running,
    /// Held by the user; never selected as due.
    Paused,
    /// A `once` job that has fired, or a repeat that exhausted its count.
    Done,
    /// The last run errored.
    Failed,
}

/// How many times a recurring job should fire before it is retired.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, Default)]
pub struct Repeat {
    /// `None` = forever; `Some(n)` = stop (and delete) after `n` firings.
    #[serde(default)]
    pub times: Option<u64>,
    /// How many firings have completed so far.
    #[serde(default)]
    pub completed: u64,
}

/// Where a run's output is sent.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "lowercase")]
pub enum DeliveryTarget {
    /// The always-on per-run Markdown file.
    File,
    /// An HTTP POST to `url`.
    Webhook { url: String },
}

/// The arguments needed to construct a fresh [`Job`]; everything else
/// ([`JobState`], `created_at`, the first `next_run_at`) is derived.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct NewJob {
    pub id: String,
    pub name: String,
    pub prompt: String,
    pub executor: ExecutorKind,
    pub script: Option<String>,
    pub schedule: Schedule,
    pub schedule_display: String,
    pub repeat: Repeat,
    pub deliver: Vec<DeliveryTarget>,
    pub workdir: Option<PathBuf>,
    pub context_from: Option<String>,
    pub codex_model: Option<String>,
    pub event_loop: Option<crate::event_loop::EventLoopPolicy>,
}

/// A scheduled job.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Job {
    /// 12 hex chars, generated by the cli when the job is added.
    pub id: String,
    pub name: String,
    /// The prompt handed to the codex/agent executor.
    pub prompt: String,
    pub executor: ExecutorKind,
    /// Shell: the command. Ao2: the spec path or inline spec.
    #[serde(default)]
    pub script: Option<String>,
    pub schedule: Schedule,
    pub schedule_display: String,
    #[serde(default)]
    pub repeat: Repeat,
    pub enabled: bool,
    pub state: JobState,
    pub created_at: DateTime<Utc>,
    #[serde(default)]
    pub next_run_at: Option<DateTime<Utc>>,
    #[serde(default)]
    pub last_run_at: Option<DateTime<Utc>>,
    #[serde(default)]
    pub last_status: Option<String>,
    #[serde(default)]
    pub last_error: Option<String>,
    /// Defaults to `[File]` when none is given.
    #[serde(default)]
    pub deliver: Vec<DeliveryTarget>,
    #[serde(default)]
    pub workdir: Option<PathBuf>,
    /// Another job's id; inject that job's last output into this prompt.
    #[serde(default)]
    pub context_from: Option<String>,
    #[serde(default)]
    pub codex_model: Option<String>,
    #[serde(default)]
    pub event_loop: Option<crate::event_loop::EventLoopPolicy>,
}

/// Errors from the store-envelope helpers.
#[derive(Debug, thiserror::Error)]
pub enum JobError {
    #[error("malformed jobs json: {0}")]
    Json(#[from] serde_json::Error),
    #[error("unsupported jobs schema_version '{found}', expected '{expected}'")]
    SchemaMismatch { found: String, expected: String },
}

impl Job {
    /// Build a fresh job: `enabled`, `Scheduled`, `created_at = now`, the first
    /// `next_run_at` computed from the schedule, and `deliver` defaulted to
    /// `[File]` when the caller passed none.
    pub fn new(spec: NewJob, now: DateTime<Utc>) -> Self {
        let next_run_at = compute_next_run(&spec.schedule, None, now);
        let deliver = if spec.deliver.is_empty() {
            vec![DeliveryTarget::File]
        } else {
            spec.deliver
        };
        Job {
            id: spec.id,
            name: spec.name,
            prompt: spec.prompt,
            executor: spec.executor,
            script: spec.script,
            schedule: spec.schedule,
            schedule_display: spec.schedule_display,
            repeat: spec.repeat,
            enabled: true,
            state: JobState::Scheduled,
            created_at: now,
            next_run_at,
            last_run_at: None,
            last_status: None,
            last_error: None,
            deliver,
            workdir: spec.workdir,
            context_from: spec.context_from,
            codex_model: spec.codex_model,
            event_loop: spec.event_loop,
        }
    }
}

/// The on-disk envelope: `{ "schema_version": ..., "jobs": [...] }`.
#[derive(Debug, Serialize, Deserialize)]
struct JobsFile {
    schema_version: String,
    jobs: Vec<Job>,
}

/// Parse the store envelope, refusing any unrecognized `schema_version`.
pub fn parse_jobs(json: &str) -> Result<Vec<Job>, JobError> {
    let file: JobsFile = serde_json::from_str(json)?;
    if file.schema_version != JOBS_SCHEMA_VERSION {
        return Err(JobError::SchemaMismatch {
            found: file.schema_version,
            expected: JOBS_SCHEMA_VERSION.to_string(),
        });
    }
    Ok(file.jobs)
}

/// Serialize jobs into the current store envelope (pretty-printed).
pub fn jobs_to_json(jobs: &[Job]) -> Result<String, JobError> {
    let file = JobsFile {
        schema_version: JOBS_SCHEMA_VERSION.to_string(),
        jobs: jobs.to_vec(),
    };
    Ok(serde_json::to_string_pretty(&file)?)
}

#[cfg(test)]
mod tests {
    use super::*;
    use chrono::TimeZone;

    fn at(y: i32, mo: u32, d: u32, h: u32, mi: u32) -> DateTime<Utc> {
        Utc.with_ymd_and_hms(y, mo, d, h, mi, 0).unwrap()
    }

    fn sample_spec() -> NewJob {
        NewJob {
            id: "0123456789ab".to_string(),
            name: "daily standup".to_string(),
            prompt: "summarize the day".to_string(),
            executor: ExecutorKind::Codex,
            script: None,
            schedule: Schedule::Interval { minutes: 60 },
            schedule_display: "every 1h".to_string(),
            repeat: Repeat::default(),
            deliver: vec![],
            workdir: None,
            context_from: None,
            codex_model: None,
            event_loop: None,
        }
    }

    #[test]
    fn new_job_has_scheduled_defaults() {
        let now = at(2026, 6, 1, 10, 0);
        let job = Job::new(sample_spec(), now);

        assert_eq!(job.state, JobState::Scheduled);
        assert!(job.enabled);
        assert_eq!(job.created_at, now);
        assert_eq!(job.last_run_at, None);
        assert_eq!(job.last_status, None);
        assert_eq!(job.repeat.completed, 0);
        // First run of an hourly interval with no last-run anchors to now + 1h.
        assert_eq!(job.next_run_at, Some(at(2026, 6, 1, 11, 0)));
    }

    #[test]
    fn new_job_defaults_delivery_to_file() {
        let now = at(2026, 6, 1, 10, 0);
        let job = Job::new(sample_spec(), now);
        assert_eq!(job.deliver, vec![DeliveryTarget::File]);
    }

    #[test]
    fn new_job_keeps_explicit_delivery() {
        let now = at(2026, 6, 1, 10, 0);
        let mut spec = sample_spec();
        spec.deliver = vec![DeliveryTarget::Webhook {
            url: "https://example.com/hook".to_string(),
        }];
        let job = Job::new(spec, now);
        assert_eq!(
            job.deliver,
            vec![DeliveryTarget::Webhook {
                url: "https://example.com/hook".to_string()
            }]
        );
    }

    #[test]
    fn jobs_round_trip_through_envelope() {
        let now = at(2026, 6, 1, 10, 0);
        let jobs = vec![Job::new(sample_spec(), now)];
        let json = jobs_to_json(&jobs).unwrap();
        let parsed = parse_jobs(&json).unwrap();
        assert_eq!(parsed, jobs);
    }

    #[test]
    fn jobs_to_json_stamps_schema_version() {
        let json = jobs_to_json(&[]).unwrap();
        assert!(json.contains("codex-cron.jobs.v1"));
    }

    #[test]
    fn parse_jobs_rejects_wrong_schema_version() {
        let json = r#"{"schema_version":"codex-cron.jobs.v999","jobs":[]}"#;
        let err = parse_jobs(json).unwrap_err();
        assert!(matches!(err, JobError::SchemaMismatch { .. }));
    }

    #[test]
    fn parse_jobs_reads_documented_format() {
        // A single job in the exact wire shape the design documents.
        let json = r#"{
          "schema_version": "codex-cron.jobs.v1",
          "jobs": [
            {
              "id": "0123456789ab",
              "name": "daily standup",
              "prompt": "summarize the day",
              "executor": "codex",
              "schedule": { "kind": "interval", "minutes": 60 },
              "schedule_display": "every 1h",
              "repeat": { "times": null, "completed": 0 },
              "enabled": true,
              "state": "scheduled",
              "created_at": "2026-06-01T10:00:00Z",
              "next_run_at": "2026-06-01T11:00:00Z",
              "deliver": [ { "type": "file" } ]
            }
          ]
        }"#;
        let jobs = parse_jobs(json).unwrap();
        assert_eq!(jobs.len(), 1);
        let j = &jobs[0];
        assert_eq!(j.id, "0123456789ab");
        assert_eq!(j.executor, ExecutorKind::Codex);
        assert_eq!(j.schedule, Schedule::Interval { minutes: 60 });
        assert_eq!(j.state, JobState::Scheduled);
        assert_eq!(j.deliver, vec![DeliveryTarget::File]);
        assert_eq!(j.next_run_at, Some(at(2026, 6, 1, 11, 0)));
    }

    #[test]
    fn executor_kind_serializes_lowercase() {
        assert_eq!(serde_json::to_string(&ExecutorKind::Ao2).unwrap(), "\"ao2\"");
        assert_eq!(
            serde_json::to_string(&ExecutorKind::Shell).unwrap(),
            "\"shell\""
        );
    }

    #[test]
    fn delivery_target_webhook_is_tagged() {
        let w = DeliveryTarget::Webhook {
            url: "https://x.test/h".to_string(),
        };
        let s = serde_json::to_string(&w).unwrap();
        assert!(s.contains("\"type\":\"webhook\""), "got {s}");
        assert!(s.contains("https://x.test/h"), "got {s}");
    }
}
